<li class="widget one-third column"><div id="dd_the_latest_news_widget-2" class="dd_the_latest_news_widget">

  <h3>
      
      News & Events      
      
                               

                  <span class="viewall">   [ <a href="../news/" title="Read All">Read All</a> ]</span>
                  
                                      
  
  </h3>
<font color=#999999>27 January 2016 - Bangkok: Memorandum of Agreement of trade corporation</font><br>

<a href="http://www.gocviet.com.vn/news/index.php#agreement" target="_self"><img src="http://www.gocviet.com.vn/news/agreement.jpg" title="27 January 2016 - Bangkok: Memorandum of Agreement of trade corporation for trade marketing support both domestic and abroad between Thailand's  entrepreneur Eastern Rice and Vietnam's entrepreneurs -  TST Group and Goc Viet Trading Co. Ltd.  Toward ASIAN and the efficiency of the cooperation between Vietnam enterprises with enterprises in ASEAN countries. Goc Viet and TST Group together creating investment opportunities to jointly overcome all challenges to increase competitive strength." border="0" width="300"></a>

<br>

<iframe width="300" height="200" src="https://www.youtube.com/embed/XTd9mUceb6Y" frameborder="0" allowfullscreen></iframe>

<iframe width="300" height="200" src="https://www.youtube.com/embed/P2_FRur-QzA" frameborder="0" allowfullscreen></iframe>
               
<iframe width="300" height="200" src="https://www.youtube.com/embed/MXv5Ru4qTyw?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>                  
<iframe width="300" height="200" src="https://www.youtube.com/embed/Z7njKux8aBw?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>
                
				
      <h3>PRESS RELEASE</h3>


				
               <ul class="newsPost_latest clearfix">
                    
                                                    <li>
                        
                                           
                           
                           <div class="post_latest">
                           
                                                            
                           
                            <div class="postDetails_latest">
                                
                       <p class="news_title"><a href="http://www.gocviet.com.vn/news/index.php#zing" target="_self" class="postTitle">Tương ớt gốc Việt cay đậm đà, an toàn cho sức khỏe</a></p>
                               
                            </div>
                            </div>
                            
    

                           
               
                      
                        
                    </li>
  
                             


                                                    <li>
                        
                                           
                           
                           <div class="post_latest">
                           
                                                            
                           
                            <div class="postDetails_latest">
                                
                       <p class="news_title"><a href="http://www.gocviet.com.vn/news/index.php#cafelover" target="_self" class="postTitle">Café Lover ! Cà phê nguyên chất (SẠCH)</a></p>
                               
                            </div>
                            </div>
                            
    

                           
               
                      
                        
                    </li>
 

 <!--                         
    
 
                         
                                                    <li>
                        
                                           
                           
                           <div class="post_latest">
                           
                                                            
                           
                            <div class="postDetails_latest">
                                
                       <p class="news_title"><a href="http://www.gocviet.com.vn/news/index.php#legend" target="_self" class="postTitle">Vi Hao’s Sriracha hot chili sauce – a sure-fire legend</a></p>
                       <p class="news_date">In baomoi.com</p>
                                
                            </div>
                            </div>
                            
    

                           
               
                      
                        
                    </li>
 
 
 
 
 
 
 
                         
                                                    <li>
                        
                                           
                           
                           <div class="post_latest">
                          
                                                            
                           
                            <div class="postDetails_latest">
                                
                       <p class="news_title"><a href="http://www.gocviet.com.vn/news/index.php#140707" target="_self" class="postTitle">Vi Hao Hot Chili Sauce– A journey to delight gourmet custormers in Vietnam and abroad</a></p>
                       <p class="news_date">In tuoitrenews.vn</p>
                                
                            </div>
                            </div>
                            
    

                           
               
                      
                        
                    </li>
					
					
                        
                                                    <li>
                        
                                           
                           
                           <div class="post_latest">
                          
                                                            
                           
                            <div class="postDetails_latest">
                                
                       <p class="news_title"><a href="http://www.gocviet.com.vn/news/index.php#130522" target="_self" class="postTitle">Truyền kỳ theo vị cay Sriracha</a></p>
                       <p class="news_date">In vietluhanh.vn</p>
                                
                            </div>
                            </div>
                            
    

                           
               
                      
                        
                    </li>					
					
                        
                                                    <li>
                        
                                           
                           
                           <div class="post_latest">
                          
                                                            
                           
                            <div class="postDetails_latest">
                                
                       <p class="news_title"><a href="http://www.gocviet.com.vn/news/index.php#141126" target="_self" class="postTitle">Tương ớt Vị Hảo - gia vị của gia đình Việt</a></p>
                       <p class="news_date">In tuoitre.vn</p>
                                
                            </div>
                            </div>
                            
    

                           
               
                      
                        
                    </li>		
					
					
-->					
								